class InboundStatus 
  FILE_PENDING = "PENDING"
  FILE_ARRIVED = "ARRIVED"
  FILE_EXTRA = "EXTRA"
  FILE_EXCEPTION = "EXCEPTION"
  BATCH_LOADING = "LOADING"
  CLAIM_LOADING = "LOADING"
  BATCH_LOADED = "LOADED"
  ARRIVAL_ONTIME = "ONTIME"
  ARRIVAL_EARLY = "EARLY"
  ARRIVAL_LATE = "LATE"  
end
